//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAModManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAModManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;OpCode&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;RuleSet&gt;
        ///		&lt;Keywords fontSize=&quot;14&quot; foreground=&quot;Yellow&quot;&gt;
        ///			&lt;Word&gt;write8&lt;/Word&gt;
        ///			&lt;Word&gt;write16&lt;/Word&gt;
        ///			&lt;Word&gt;write32&lt;/Word&gt;
        ///			&lt;Word&gt;writefloat&lt;/Word&gt;
        ///			&lt;Word&gt;writenop&lt;/Word&gt;
        ///			&lt;Word&gt;writereg8&lt;/Word&gt;
        ///			&lt;Word&gt;writereg16&lt;/Word&gt;
        ///			&lt;Word&gt;writereg32&lt;/Word&gt;
        ///			&lt;Word&gt;writenopreg&lt;/Word&gt;
        ///
        ///			&lt;Word&gt;readreg8&lt;/Word&gt;
        ///			&lt;Word&gt;readreg16&lt;/Word&gt;
        ///			&lt;Word&gt;readreg32&lt;/Word&gt;
        ///
        ///			&lt;Word&gt;newregs&lt;/Word&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpCodeSyntaxDark {
            get {
                return ResourceManager.GetString("OpCodeSyntaxDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;OpCode&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;RuleSet&gt;
        ///		&lt;Keywords fontSize=&quot;14&quot; foreground=&quot;DarkGoldenrod&quot;&gt;
        ///			&lt;Word&gt;write8&lt;/Word&gt;
        ///			&lt;Word&gt;write16&lt;/Word&gt;
        ///			&lt;Word&gt;write32&lt;/Word&gt;
        ///			&lt;Word&gt;writefloat&lt;/Word&gt;
        ///			&lt;Word&gt;writenop&lt;/Word&gt;
        ///			&lt;Word&gt;writereg8&lt;/Word&gt;
        ///			&lt;Word&gt;writereg16&lt;/Word&gt;
        ///			&lt;Word&gt;writereg32&lt;/Word&gt;
        ///			&lt;Word&gt;writenopreg&lt;/Word&gt;
        ///
        ///			&lt;Word&gt;readreg8&lt;/Word&gt;
        ///			&lt;Word&gt;readreg16&lt;/Word&gt;
        ///			&lt;Word&gt;readreg32&lt;/Word&gt;
        ///
        ///			&lt;Word&gt;newregs&lt;/Wor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpCodeSyntaxLight {
            get {
                return ResourceManager.GetString("OpCodeSyntaxLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SA2FileHashes {
            get {
                object obj = ResourceManager.GetObject("SA2FileHashes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SA2ModLoader {
            get {
                object obj = ResourceManager.GetObject("SA2ModLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SADXFileHashes {
            get {
                object obj = ResourceManager.GetObject("SADXFileHashes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SADXModLoader {
            get {
                object obj = ResourceManager.GetObject("SADXModLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/x-hax/sa2-mod-loader/releases/latest.
        /// </summary>
        internal static string URL_SA2_DL {
            get {
                return ResourceManager.GetString("URL_SA2_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/x-hax/sadx-mod-loader/releases/latest.
        /// </summary>
        internal static string URL_SADX_DL {
            get {
                return ResourceManager.GetString("URL_SADX_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nightly.link/X-Hax/SA-Mod-Manager/suites/{0}/artifacts/{1}.
        /// </summary>
        internal static string URL_SAMM_UPDATE {
            get {
                return ResourceManager.GetString("URL_SAMM_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
