# Win32-specific CFLAGS/CXXFLAGS.
# For Microsoft Visual C++ compilers.

# Basic platform flags.
SET(MODLOADER_C_FLAGS_WIN32 "${MODLOADER_C_FLAGS_WIN32} -Zc:wchar_t")

# Append the CFLAGS.
SET(MODLOADER_C_FLAGS_COMMON "${MODLOADER_C_FLAGS_COMMON} ${MODLOADER_C_FLAGS_WIN32}")
SET(MODLOADER_CXX_FLAGS_COMMON "${MODLOADER_CXX_FLAGS_COMMON} ${MODLOADER_C_FLAGS_WIN32}")
UNSET(MODLOADER_C_FLAGS_WIN32)
